app:
  allowed-origins: http://localhost:4200
  
spring:
  profiles:
    active: dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/graph_ql_poc_store?ssl=false
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  hibernate:
    ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    
server:
  port: 8080